name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: file
    attributes:
      label: File(s) with issue
      description: Which file(s) contain the bug?
      placeholder: "e.g., categories/aerial_work_platforms.json"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the issue? What did you expect to happen?
      placeholder: "Describe the bug clearly and concisely"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: "1. Go to '...'
2. Look at '...'
3. See error"
    validations:
      required: false
  - type: dropdown
    id: validation
    attributes:
      label: Validation
      description: Did you run the validation script?
      options:
        - "Yes, and it passed"
        - "Yes, and it failed"
        - "No"
    validations:
      required: true
