name: Codex attribute proposer
on:
  workflow_dispatch:      # manual run button
  schedule:
    - cron: "0 3 * * *"   # nightly 03:00 UTC
jobs:
  populate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install jsonschema openai requests
      - name: Run Codex populate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN:   ${{ secrets.BOT_GITHUB_TOKEN }}
        run: python scripts/codex_populate.py
