name: Codex attribute proposer
on:
  workflow_dispatch:      # manual run button
  schedule:
    - cron: "0 3 * * *"   # nightly 03:00 UTC
jobs:
  populate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false      # we will push with installation token
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install jsonschema openai requests pyjwt[crypto]
      - name: Run Codex populate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GH_APP_ID:           ${{ secrets.GH_APP_ID }}
          GH_APP_PRIVATE_KEY:  ${{ secrets.GH_APP_PRIVATE_KEY }}
        run: python scripts/codex_populate.py
